{% set name = "jupyterlite-ai" %}
{% set version = "0.7.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlite_ai-{{ version }}.tar.gz
  sha256: c851c93be66797792b41dbb403cd8bca9899090e3eeca54c3b5ae0bd52217979

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-jupyter-builder >=0.5
    - hatchling >=1.5.0
    - jupyterlab >=4.4.0,<5
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - python >={{ python_min }}
    - jupyter-secrets-manager >=0.4,<0.5

test:
  imports:
    - jupyterlite_ai
  requires:
    - jupyterlab >=4.4.0,<5
    - python {{ python_min }}
    - pip
    - m2-grep  # [win]
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "@jupyterlite/ai.*OK"

about:
  home: https://github.com/jupyterlite/ai
  summary: AI code completions and chat for JupyterLite
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brichet
    - jtpio
